news_sites:
 eluniversal:
  url: https://www.eluniversal.com
  queries:
   homepage_article_links: '//a[@class="title"]/@href'
   article_body: '//div[@class="note-text"]/div[not(@class)]/text()'
   article_title: '//header//h2[@class="title"]/a/text()'
 elpais:
  url: https://elpais.com
  queries:
   homepage_article_links: "//article//a[not(@class)]/@href"
   article_body: '//article//div[@id="ctn_article_body"]/p/text()'
   article_title: "//article/header/div/h1/text()"
